openapi: 3.0.0
info:
  title: Your API
  description: API documentation for Your API
  version: 1.0.0
paths:
  /signup:
    post:
      summary: Create a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                email:
                  type: string
                company:
                  type: string
                password:
                  type: string
                
                
      responses:
        '201':
          description: User created successfully
        '400':
          description: Bad request
  /login:
    post:
      summary: Login with username and password
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
                
      responses:
        '200':
          description: Successful login
        '401':
          description: Unauthorized
